"""Department definitions for Carbon6 TUI."""

DEPARTMENTS = {
    "development": {
        "name": "Development",
        "icon": ">>",
        "color": "cyan",
        "tagline": "Build. Ship. Scale.",
        "lead_agent": "TECHNE",
        "lead_desc": "Technology & Development",
        "agents": [
            ("TECHNE", "Lead", "Full-stack development, system architecture"),
            ("TECHNE-ARCHITECT", "Sub", "System design & architecture"),
            ("TECHNE-FRONTEND", "Sub", "UI/UX implementation"),
            ("TECHNE-BACKEND", "Sub", "API & database engineering"),
            ("TECHNE-BLOCKCHAIN", "Sub", "Smart contracts & Web3"),
            ("TECHNE-DEVOPS", "Sub", "CI/CD & infrastructure"),
            ("TECHNE-AI", "Sub", "ML integration & AI ops"),
        ],
        "tools": [
            {"name": "git-flow", "desc": "Automated git workflow", "installed": True},
            {"name": "ci-pipeline", "desc": "CI/CD pipeline manager", "installed": True},
            {"name": "api-scaffold", "desc": "REST/GraphQL API generator", "installed": False},
            {"name": "db-migrate", "desc": "Database migration toolkit", "installed": False},
            {"name": "docker-compose", "desc": "Container orchestration", "installed": True},
            {"name": "test-runner", "desc": "Automated test suite runner", "installed": False},
            {"name": "code-review", "desc": "AI-powered code review", "installed": False},
            {"name": "perf-profiler", "desc": "Performance profiling tool", "installed": False},
        ],
        "workflows": [
            "full-stack-build", "api-design", "database-migration",
            "ci-cd-pipeline", "security-audit", "code-review",
            "smart-contract-deploy",
        ],
        "quick_cmds": [
            ("gh-auto status", "Repo status"),
            ("gh-auto ci", "CI/CD checks"),
            ("node --version", "Node version"),
            ("docker ps", "Running containers"),
        ],
    },
    "marketing": {
        "name": "Marketing",
        "icon": ">>",
        "color": "green",
        "tagline": "Reach. Convert. Grow.",
        "lead_agent": "MERCATOR",
        "lead_desc": "Marketing & Growth",
        "agents": [
            ("MERCATOR", "Lead", "Marketing strategy & growth hacking"),
            ("MERCATOR-STRATEGY", "Sub", "GTM planning & positioning"),
            ("MERCATOR-GROWTH", "Sub", "Performance marketing & funnels"),
            ("MERCATOR-SOCIAL", "Sub", "Community & influencer management"),
            ("MERCATOR-CONTENT", "Sub", "Marketing content & copywriting"),
            ("CULTURA", "Support", "Brand & culture alignment"),
            ("CULTURA-BRAND", "Sub", "Brand psychology & identity"),
        ],
        "tools": [
            {"name": "campaign-mgr", "desc": "Campaign lifecycle manager", "installed": False},
            {"name": "seo-toolkit", "desc": "SEO analysis & optimization", "installed": False},
            {"name": "social-scheduler", "desc": "Social media post scheduler", "installed": False},
            {"name": "analytics-dash", "desc": "Marketing analytics dashboard", "installed": False},
            {"name": "ab-testing", "desc": "A/B test framework", "installed": False},
            {"name": "email-builder", "desc": "Email template builder", "installed": False},
            {"name": "content-calendar", "desc": "Content planning calendar", "installed": False},
        ],
        "workflows": [
            "campaign-launch", "ab-test-analysis", "seo-optimization",
            "content-calendar", "influencer-outreach", "brand-audit",
        ],
        "quick_cmds": [
            ("gh-auto status", "Repo status"),
            ("curl -s -o /dev/null -w '%{http_code}' https://carbon-room.onrender.com", "Site health"),
        ],
    },
    "back_office": {
        "name": "Back Office",
        "icon": ">>",
        "color": "yellow",
        "tagline": "Finance. Operations. Compliance.",
        "lead_agent": "AURUM + PRAXIS",
        "lead_desc": "Finance, Operations & Compliance",
        "agents": [
            ("AURUM", "Lead", "Finance & treasury management"),
            ("AURUM-CONTROLLER", "Sub", "Bookkeeping & GAAP compliance"),
            ("AURUM-ANALYST", "Sub", "Variance analysis & forecasting"),
            ("AURUM-TAX", "Sub", "Tax compliance & planning"),
            ("AURUM-TREASURY", "Sub", "Cash flow management"),
            ("PRAXIS", "Lead", "Operations & project execution"),
            ("PRAXIS-EXECUTOR", "Sub", "Task execution & tracking"),
            ("PRAXIS-WORKFLOW", "Sub", "Process automation"),
            ("TRUST_DIRECTOR", "Lead", "Compliance & trust architecture"),
            ("TRUST-COMPLIANCE", "Sub", "Regulatory compliance"),
            ("TRUST-ASSET", "Sub", "Asset protection"),
        ],
        "tools": [
            {"name": "invoice-gen", "desc": "Invoice & billing generator", "installed": False},
            {"name": "expense-tracker", "desc": "Expense categorization & tracking", "installed": False},
            {"name": "tax-calc", "desc": "Tax estimation & compliance", "installed": False},
            {"name": "project-tracker", "desc": "Project timeline & milestones", "installed": False},
            {"name": "contract-mgr", "desc": "Contract lifecycle manager", "installed": False},
            {"name": "payroll", "desc": "Payroll & revenue split calculator", "installed": False},
            {"name": "audit-trail", "desc": "Compliance audit logging", "installed": True},
        ],
        "workflows": [
            "month-end-close", "variance-analysis", "cash-flow-projection",
            "tax-compliance", "project-kickoff", "sprint-planning",
            "resource-allocation", "risk-assessment",
        ],
        "quick_cmds": [
            ("python3 /root/memory-system/scripts/memory.py stats", "Memory stats"),
            ("crontab -l 2>/dev/null | grep -v '^#' | grep '.'", "Active crons"),
        ],
    },
    "creative": {
        "name": "Creative",
        "icon": ">>",
        "color": "magenta",
        "tagline": "Create. Produce. Inspire.",
        "lead_agent": "MELODIA",
        "lead_desc": "Creative & Media Production",
        "agents": [
            ("MELODIA", "Lead", "Content creation & media production"),
            ("MELODIA-CONTENT", "Sub", "Copywriting & scripts"),
            ("MELODIA-VIDEO", "Sub", "Video production & editing"),
            ("MELODIA-AUDIO", "Sub", "Music & podcast production"),
            ("MELODIA-VISUAL", "Sub", "Design & visual assets"),
            ("GENESIS-UI", "Support", "Dynamic UI generation"),
            ("GENESIS-UI-RENDERER", "Sub", "React component generation"),
        ],
        "tools": [
            {"name": "asset-pipeline", "desc": "Media asset processing pipeline", "installed": False},
            {"name": "brand-kit", "desc": "Brand guidelines & asset library", "installed": False},
            {"name": "video-encoder", "desc": "Video transcoding & optimization", "installed": False},
            {"name": "design-system", "desc": "Component design system generator", "installed": False},
            {"name": "image-optimizer", "desc": "Image compression & resizing", "installed": False},
            {"name": "font-manager", "desc": "Typography & font management", "installed": False},
        ],
        "workflows": [
            "brand-identity", "content-production", "video-editing",
            "audio-mastering", "design-system",
        ],
        "quick_cmds": [
            ("gh-auto status", "Repo status"),
        ],
    },
    "data": {
        "name": "Data & Analytics",
        "icon": ">>",
        "color": "blue",
        "tagline": "Measure. Analyze. Decide.",
        "lead_agent": "DATUM",
        "lead_desc": "Data Engineering & Business Intelligence",
        "agents": [
            ("DATUM", "Lead", "Data engineering & analytics"),
            ("DATUM-ENGINEER", "Sub", "Data pipeline construction"),
            ("DATUM-ANALYST", "Sub", "BI analysis & reporting"),
            ("DATUM-VISUALIZER", "Sub", "Dashboard & visualization"),
            ("DATUM-WAREHOUSE", "Sub", "Data warehouse management"),
            ("SOPHIA", "Support", "Research & deep analysis"),
            ("SOPHIA-RESEARCH", "Sub", "Deep research & analysis"),
            ("SOPHIA-INTEL", "Sub", "Competitive intelligence"),
        ],
        "tools": [
            {"name": "etl-pipeline", "desc": "Extract-Transform-Load pipeline", "installed": False},
            {"name": "sql-runner", "desc": "SQL query runner & analyzer", "installed": False},
            {"name": "report-gen", "desc": "Automated report generator", "installed": False},
            {"name": "data-quality", "desc": "Data validation & quality checks", "installed": False},
            {"name": "redis-monitor", "desc": "Redis cache monitoring", "installed": True},
            {"name": "log-analyzer", "desc": "Log parsing & pattern detection", "installed": False},
        ],
        "workflows": [
            "due-diligence", "competitive-intel", "market-analysis",
            "tech-assessment", "vendor-evaluation",
        ],
        "quick_cmds": [
            ("redis-cli info keyspace 2>/dev/null", "Redis keyspace"),
            ("python3 /root/memory-system/scripts/memory.py stats", "Memory stats"),
        ],
    },
    "security": {
        "name": "Security",
        "icon": ">>",
        "color": "red",
        "tagline": "Protect. Detect. Respond.",
        "lead_agent": "AEGIS",
        "lead_desc": "Security Architecture & Threat Detection",
        "agents": [
            ("AEGIS", "Lead", "Security architecture & threat detection"),
            ("AEGIS-SENTINEL", "Sub", "Real-time threat monitoring"),
            ("AEGIS-GUARDIAN", "Sub", "Access control & authentication"),
            ("AEGIS-INQUISITOR", "Sub", "Incident response & forensics"),
            ("AEGIS-FORTRESS", "Sub", "Infrastructure hardening"),
            ("AEGIS-PENETRATOR", "Sub", "Penetration testing"),
        ],
        "tools": [
            {"name": "vuln-scanner", "desc": "Vulnerability scanning", "installed": False},
            {"name": "secret-vault", "desc": "Secret & credential management", "installed": True},
            {"name": "ssl-monitor", "desc": "SSL certificate monitoring", "installed": False},
            {"name": "firewall-mgr", "desc": "Firewall rule management", "installed": False},
            {"name": "access-audit", "desc": "Access log auditing", "installed": False},
            {"name": "incident-mgr", "desc": "Incident response runbook", "installed": False},
        ],
        "workflows": [
            "regulatory-check", "policy-review", "contract-analysis",
            "risk-assessment", "audit-trail", "incident-response",
        ],
        "quick_cmds": [
            ("gh auth status 2>&1 | head -5", "GitHub auth status"),
            ("ss -tlnp 2>/dev/null | head -10", "Open ports"),
        ],
    },
    "client_success": {
        "name": "Client Success",
        "icon": ">>",
        "color": "white",
        "tagline": "Onboard. Deliver. Retain.",
        "lead_agent": "CUSTOS",
        "lead_desc": "Client Relations & Project Delivery",
        "agents": [
            ("CUSTOS", "Lead", "Client relations & project delivery"),
            ("CUSTOS-SUCCESS", "Sub", "Client relationship management"),
            ("CUSTOS-SALES", "Sub", "Business development & proposals"),
            ("CUSTOS-DELIVERY", "Sub", "Project handoff & QA"),
            ("CUSTOS-RETENTION", "Sub", "Retention & satisfaction"),
            ("LEXIS", "Support", "Language & communication"),
            ("LEXIS-DOCUMENTATION", "Sub", "Technical writing & docs"),
        ],
        "tools": [
            {"name": "crm-lite", "desc": "Client relationship tracker", "installed": False},
            {"name": "proposal-gen", "desc": "Proposal & SOW generator", "installed": False},
            {"name": "onboard-flow", "desc": "Client onboarding automation", "installed": False},
            {"name": "feedback-loop", "desc": "Client feedback & NPS tracker", "installed": False},
            {"name": "handoff-mgr", "desc": "Project delivery & handoff", "installed": False},
        ],
        "workflows": [
            "client-onboarding", "requirement-gathering", "proposal-generation",
            "sow-creation", "change-order", "satisfaction-survey",
        ],
        "quick_cmds": [
            ("gh-auto status", "Repo status"),
        ],
    },
}
